### ISSUE TITLE
GitHub zip path changed -- breaking composer installs

### ISSUE THREAD

**Issue by requenym** [byalextran/DnsMadeEasy#10]
Alex,

Love this lib -- can you update the dist info so composer to happily install your package again?
- Installing a1extran/dns-made-easy (1.1.0)
  Downloading: connection...
  Failed to download a1extran/dns-made-easy from dist: The "https://api.github.com/repos/a1extran/DnsMadeEasy/zipball/a1fbe3ddafdd0f43e51fa9e3c0be7e31c155d015" file could not be downloaded (HTTP/1.1 404 Not Found)

**Comment by byalextran** [comment]
Aha, that's what I get for changing my GitHub username. I've pushed a new version with the updated path and also updated the package for Composer. Thanks for the heads up! 

FYI, Composer will still refer to the library using my old username (a1extran/dns-made-easy).
